-- Snapshot of the public schema of the Supabase project "ziradev", taken 2026-10-02.
-- STRUCTURE ONLY (no rows). Generated from an information_schema/pg_catalog export, so it is a
-- faithful but not byte-identical rebuild. Used by supabase/tests to run the tenant migrations
-- against the real table list. Regenerate when the live schema changes.


create sequence if not exists public.hr_contract_settings_id_seq;

create sequence if not exists public.hr_employment_status_id_seq;

create sequence if not exists public.hr_leave_schedules_id_seq;

create sequence if not exists public.hr_lifecycle_history_id_seq;

create sequence if not exists public.hr_notifications_id_seq;

create sequence if not exists public.hr_salary_advances_id_seq;

create sequence if not exists public.hr_suspensions_id_seq;

create sequence if not exists public.hr_termination_interviews_id_seq;

create sequence if not exists public.hr_terminations_id_seq;

create table public."Employee_Records_Duplicate" (
  "created_at" timestamptz default now(),
  "Employee Number" text,
  "Official Email" text,
  "Town" text
);

create table public."assets" (
  "purchase_date" date,
  "purchase_value" numeric,
  "id" uuid default uuid_generate_v4() not null,
  "updated_at" timestamp default now(),
  "created_at" timestamp default now(),
  "next_maintenance" date,
  "last_maintenance" date,
  "warranty_expiry" date,
  "model" text,
  "status" text,
  "condition" text,
  "location" text,
  "assigned_to" text,
  "notes" text,
  "asset_name" text,
  "asset_tag" text,
  "category" text,
  "serial_number" text,
  "brand" text
);

create table public."attendance_logs" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "login_time" timestamptz,
  "logout_time" timestamptz,
  "geolocation" jsonb,
  "employee_number" text,
  "status" text
);

create table public."audit_log" (
  "id" uuid default uuid_generate_v4() not null,
  "record_id" uuid,
  "old_data" jsonb,
  "new_data" jsonb,
  "performed_by" uuid,
  "performed_at" timestamptz default now(),
  "user_agent" text,
  "action_type" varchar,
  "table_name" varchar,
  "ip_address" varchar
);

create table public."branch_performance" (
  "portfolio_at_risk" numeric,
  "total_active_loans" integer,
  "loans_in_arrears" integer,
  "arrears_amount" numeric,
  "new_loans" integer,
  "updated_at" timestamp default now(),
  "total_loans_disbursed" integer,
  "created_at" timestamp default now(),
  "staff_count" integer,
  "disbursement_target" integer,
  "total_collection" numeric,
  "collection_target" numeric,
  "average_tat" numeric,
  "total_par" numeric,
  "id" integer generated by default as identity not null,
  "branch_id" bigint,
  "date" date,
  "portfolio_size" numeric,
  "client_dropout_rate" numeric,
  "new_clients" integer,
  "active_clients" integer,
  "loan_officer_count" integer,
  "period" text,
  "portfolio_quality" text
);

create table public."channel_members" (
  "channel_id" uuid,
  "user_id" uuid,
  "joined_at" timestamptz default now(),
  "last_read_at" timestamptz,
  "is_muted" boolean default false,
  "id" uuid default uuid_generate_v4() not null,
  "role" text default 'member'::text
);

create table public."channels" (
  "is_private" boolean default false,
  "created_by" uuid,
  "updated_at" timestamptz default now(),
  "created_at" timestamptz default now(),
  "id" uuid default uuid_generate_v4() not null,
  "job_title" text,
  "description" text,
  "type" text,
  "name" text
);

create table public."client_visits" (
  "visit_id" bigint generated by default as identity not null,
  "visit_date" date default CURRENT_DATE,
  "next_visit_date" date,
  "branch_id" bigint,
  "created_at" timestamptz default now(),
  "employee_id" text,
  "client_id" text,
  "purpose" text,
  "outcome" text,
  "next_action" text,
  "location" text
);

create table public."clients" (
  "date_of_birth" date,
  "monthly_income" numeric,
  "registration_date" date default CURRENT_DATE,
  "branch_id" bigint,
  "created_at" timestamptz default now(),
  "client_id" text not null,
  "first_name" text,
  "last_name" text,
  "id_number" text,
  "gender" text,
  "marital_status" text,
  "phone_number" text,
  "email" text,
  "address" text,
  "town" text,
  "postal_code" text,
  "occupation" text,
  "status" text default 'Active'::text,
  "loan_officer" text
);

create table public."company_events" (
  "id" uuid default gen_random_uuid() not null,
  "date" date not null,
  "created_at" timestamptz default now() not null,
  "title" text not null,
  "description" text,
  "created_by" text
);

create table public."company_logo" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "image_url" text,
  "company_name" text,
  "company_tagline" text
);

create table public."dependents" (
  "id" bigint generated by default as identity not null,
  "date_birth" date,
  "created_at" timestamptz default now(),
  "Employee Number" text,
  "full_name" text,
  "relationship" text
);

create table public."email_logs" (
  "id" uuid default uuid_generate_v4() not null,
  "sent_at" timestamptz,
  "sent_by" uuid,
  "bounced_at" timestamptz,
  "webhook_received_at" timestamptz,
  "request_id" bigint,
  "created_at" timestamptz default now(),
  "body" text,
  "subject" text,
  "sent_to" text,
  "email_type" text,
  "status" text,
  "error_message" text,
  "Employee Number" text,
  "employee_id" text,
  "bounce_reason" text,
  "last_webhook_event" text,
  "message_id" text,
  "resend_id" text
);

create table public."emergency_contact" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "Employee Number" text,
  "full_name" text,
  "relationship" text,
  "phone_number" text,
  "email" text
);

create table public."employee_performance" (
  "id" bigint generated by default as identity not null,
  "date" date,
  "total_clients" integer,
  "retained_clients" integer,
  "new_clients_active" integer,
  "new_clients_inactive" integer,
  "retained_active" integer,
  "retained_inactive" integer,
  "total_active" integer,
  "total_inactive" integer,
  "no_of_disb" integer,
  "disb_amount" numeric,
  "targeted_disb_no" integer,
  "targeted_disb_amount" numeric,
  "targeted_olb" numeric,
  "actual_olb" numeric,
  "collected_loan_amount" numeric,
  "overdue_loans" integer,
  "average_loan_size" numeric,
  "loan_recovery_rate" numeric,
  "client_satisfaction_score" numeric,
  "portfolio_at_risk" numeric,
  "total_active_loans" integer,
  "loans_in_arrears" integer,
  "arrears_amount" numeric,
  "new_loans" integer,
  "tat_average" numeric,
  "working_days" integer,
  "attendance_days" integer,
  "portfolio_size" numeric,
  "par_amount" numeric,
  "collection_target" numeric,
  "collection_amount" numeric,
  "field_visits_target" integer,
  "disbursement_target" integer,
  "clients_visited" integer,
  "created_at" timestamptz default now(),
  "employee_id" text,
  "full_name" text,
  "branch" text,
  "period" text
);

create table public."employees" (
  "ID Number" bigint,
  "created_at" timestamptz default now(),
  "internship_start_date" date,
  "Basic Salary" numeric,
  "Employee Id" smallint,
  "Middle Name" text,
  "Last Name" text,
  "Work Email" text,
  "Town" text,
  "Branch" text,
  "Office" text,
  "Job Title" text,
  "Work Mobile" text,
  "Start Date" text,
  "Personal Mobile" text,
  "house_allowance" text,
  "travel_allowance" text,
  "bonus" text,
  "overtime" text,
  "hardship" text,
  "manager_email" text,
  "regional_manager" text,
  "Entity" text,
  "Employee Type" text,
  "Job Group" text,
  "Job Level" text,
  "Type of Identification" text,
  "Payroll Number" text,
  "Mobile Number" text,
  "Alternative Mobile Number" text,
  "Internship End Date" text,
  "Probation Start Date" text,
  "Probation End Date" text,
  "Contract Start Date" text,
  "Contract End Date" text,
  "Termination Date" text,
  "Manager" text,
  "Leave Approver" text,
  "Alternate Approver" text,
  "Personal Email" text,
  "Date of Birth" text,
  "Gender" text,
  "Marital Status" text,
  "Country" text default 'Kenya'::text,
  "Postal Address" text,
  "Postal Code" text,
  "Postal Location" text,
  "City" text,
  "Area" text,
  "Road" text,
  "House Number" text,
  "Tax PIN" text,
  "NHIF Number" text,
  "SHIF Number" text,
  "NSSF Number" text,
  "WIBA" text,
  "Pension Start Date" text,
  "Employee AVC" text,
  "Employer AVC" text,
  "Pension Deduction" text,
  "NSSF Deduction" text,
  "NHIF Deduction" text,
  "Housing Levy Deduction" text,
  "Tax Exempted" text,
  "Disability Cert No" text,
  "Account Number" text,
  "Bank" text,
  "Bank Branch" text,
  "passport_number" text,
  "blood_group" text,
  "religion" text,
  "second_level_leave_approver" text,
  "alternate_second_level_approver" text,
  "NITA" text,
  "NITA Deductions" text,
  "HELB" text,
  "HELB option" text,
  "account_number_name" text,
  "payment_method" text,
  "Currency" text default 'KES'::text,
  "Profile Image" text,
  "Status" text default 'Active'::text,
  "Role" text default 'STAFF'::text,
  "Employee Number" text not null,
  "First Name" text
);

create table public."expenses" (
  "id" uuid default uuid_generate_v4() not null,
  "amount" numeric,
  "date" date default CURRENT_DATE,
  "approved_date" date,
  "recommended_date" timestamptz,
  "created_at" timestamptz default now(),
  "title" text,
  "category" text,
  "description" text,
  "status" text default 'pending'::text,
  "receipt" text,
  "submitted_by" text default 'Expense Proposer'::text,
  "location" text,
  "branch" text,
  "department" text,
  "expense_type" text,
  "employee_id" text,
  "employee_full_name" text,
  "approved_by" text,
  "rejection_reason" text,
  "rec_reason" text,
  "recommended_by" text,
  "region" text,
  "avatar" text default 'EP'::text
);

create table public."holidays" (
  "id" uuid default uuid_generate_v4() not null,
  "date" date,
  "recurring" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "name" text
);

create table public."hr_contract_settings" (
  "id" integer default nextval('hr_contract_settings_id_seq'::regclass) not null,
  "default_probation_months" integer default 3,
  "default_contract_months" integer default 12,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "tenant_id" text
);

create table public."hr_employment_status" (
  "id" integer default nextval('hr_employment_status_id_seq'::regclass) not null,
  "joining_date" date,
  "probation_duration_months" integer default 3,
  "contract_duration_months" integer default 12,
  "probation_end_date" date,
  "contract_end_date" date,
  "is_confirmed" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "employment_type" text,
  "notes" text
);

create table public."hr_leave_schedules" (
  "id" integer default nextval('hr_leave_schedules_id_seq'::regclass) not null,
  "leave_start_date" date,
  "leave_end_date" date,
  "leave_days" integer,
  "notify_5days" boolean default true,
  "notify_1day" boolean default true,
  "created_at" timestamptz default now(),
  "Employee Number" text,
  "leave_type" text,
  "status" text default 'Scheduled'::text,
  "notes" text
);

create table public."hr_lifecycle_history" (
  "id" integer default nextval('hr_lifecycle_history_id_seq'::regclass) not null,
  "event_date" timestamptz default now(),
  "old_value" jsonb,
  "new_value" jsonb,
  "created_at" timestamptz default now(),
  "Employee Number" text,
  "event_type" text,
  "notes" text,
  "performed_by" text
);

create table public."hr_notifications" (
  "id" bigint default nextval('hr_notifications_id_seq'::regclass) not null,
  "end_date" date,
  "days_remaining" integer,
  "is_read_admin" boolean default false not null,
  "is_read_staff" boolean default false not null,
  "email_sent" boolean default false not null,
  "created_at" timestamptz default now() not null,
  "employee_number" text not null,
  "employee_name" text,
  "work_email" text,
  "notification_type" text not null,
  "title" text not null,
  "message" text not null
);

create table public."hr_salary_advances" (
  "id" integer default nextval('hr_salary_advances_id_seq'::regclass) not null,
  "advance_date" date not null,
  "advance_amount" numeric not null,
  "monthly_deduction" numeric not null,
  "total_repaid" numeric default 0,
  "remaining_balance" numeric default 0,
  "is_completed" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "notes" text
);

create table public."hr_suspensions" (
  "id" integer default nextval('hr_suspensions_id_seq'::regclass) not null,
  "suspension_date" date not null,
  "duration_days" integer,
  "auto_reactivate" boolean default false,
  "reactivation_date" date,
  "is_active" boolean default true,
  "exclude_from_payroll" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "suspension_reason" text,
  "notes" text,
  "performed_by" text
);

create table public."hr_termination_interviews" (
  "id" integer default nextval('hr_termination_interviews_id_seq'::regclass) not null,
  "interview_date" timestamptz,
  "is_completed" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "interviewer" text,
  "interview_notes" text,
  "document_url" text
);

create table public."hr_terminations" (
  "id" integer default nextval('hr_terminations_id_seq'::regclass) not null,
  "termination_date" date not null,
  "is_archived" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "termination_type" text,
  "termination_reason" text,
  "document_url" text,
  "final_payroll_status" text default 'Pending'::text,
  "clearance_status" text default 'Pending'::text,
  "performed_by" text
);

create table public."incident_reports" (
  "id" uuid default uuid_generate_v4() not null,
  "is_anonymous" boolean default false not null,
  "incident_date" date,
  "reviewed_at" timestamptz,
  "resolved_at" timestamptz,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "employee_number" text,
  "incident_type" text not null,
  "severity" text not null,
  "title" text not null,
  "description" text not null,
  "location" text,
  "witnesses" text,
  "evidence_urls" text[],
  "status" text default 'new'::text,
  "admin_notes" text,
  "reviewed_by" text,
  "resolution" text
);

create table public."job_applications" (
  "id" uuid default uuid_generate_v4() not null,
  "job_posting_id" uuid,
  "reviewed_at" timestamptz,
  "applied_at" timestamptz default now(),
  "user_id" uuid,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "employee_number" text,
  "cover_letter" text,
  "additional_info" text,
  "status" text default 'pending'::text,
  "reviewed_by" text,
  "admin_notes" text,
  "first_name" text,
  "last_name" text,
  "email" text,
  "phone" text,
  "id_number" text,
  "nationality" text,
  "county" text,
  "constituency" text,
  "postal_code" text,
  "address" text,
  "department" text,
  "position" text,
  "preferred_location" text,
  "available_start_date" text,
  "education" text,
  "university" text,
  "graduation_year" text,
  "work_experience" text,
  "previous_company" text,
  "previous_role" text,
  "previous_salary" text,
  "expected_salary" text,
  "skills" text,
  "languages" text,
  "markets_worked" text,
  "resume_file_name" text,
  "resume_file_url" text,
  "references" text,
  "why_joining_us" text
);

create table public."job_positions" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "title" text,
  "department" text,
  "type" text,
  "branch" text,
  "status" text default 'open'::text,
  "applications" text default '0'::text
);

create table public."job_postings" (
  "id" uuid default uuid_generate_v4() not null,
  "application_deadline" date,
  "posted_at" timestamptz default now(),
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "job_title" text not null,
  "department" text not null,
  "location" text,
  "job_type" text not null,
  "job_level" text,
  "description" text not null,
  "requirements" text not null,
  "responsibilities" text,
  "salary_range" text,
  "benefits" text,
  "status" text default 'open'::text,
  "posted_by" text
);

create table public."kenya_branches" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "Town" text,
  "Area" text,
  "Branch Office" text
);

create table public."kenya_branches_duplicate" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "Town" text,
  "Branch Office" text,
  "Area" text
);

create table public."kenya_office_locations" (
  "id" uuid default uuid_generate_v4() not null,
  "total_positions" integer,
  "critically_needed" integer,
  "urgent_positions" integer,
  "is_active" boolean default true,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "name" text,
  "location" text,
  "hiring_status" text default 'active'::text,
  "contact_email" text,
  "contact_phone" text,
  "address" text,
  "town" text,
  "county" text,
  "country" text default 'Kenya'::text
);

create table public."leave_application" (
  "id" uuid default uuid_generate_v4() not null,
  "time_added" timestamptz default now(),
  "days" bigint,
  "recommendation_notes" text,
  "recstatus" text,
  "region" text,
  "Employee Number" text,
  "Application Type" text,
  "reason" text,
  "Leave Type" text,
  "Start Date" text,
  "status" text,
  "Office Branch" text,
  "name" text,
  "End Date" text,
  "type" text,
  "notes" text
);

create table public."leave_balance_adjustments" (
  "id" uuid default gen_random_uuid() not null,
  "leave_balance_id" uuid not null,
  "delta_days" numeric not null,
  "used_days_before" numeric not null,
  "used_days_after" numeric not null,
  "accrued_days_before" numeric not null,
  "accrued_days_after" numeric not null,
  "created_at" timestamptz default now() not null,
  "change_type" text not null,
  "reason" text
);

create table public."leave_balances" (
  "id" uuid default gen_random_uuid() not null,
  "leave_type_id" uuid not null,
  "year" integer not null,
  "accrued_days" numeric default 0 not null,
  "used_days" numeric default 0 not null,
  "carried_over_days" numeric default 0 not null,
  "remaining_days" numeric generated always as (accrued_days + carried_over_days - used_days) stored,
  "monthly_accrual" numeric default 0 not null,
  "last_accrual_date" date,
  "updated_at" timestamptz default now() not null,
  "month" integer default 0 not null,
  "employee_number" text not null
);

create table public."leave_policies" (
  "id" uuid default gen_random_uuid() not null,
  "leave_type_id" uuid not null,
  "days_allotted" numeric,
  "carry_forward_max_days" numeric default 0 not null,
  "effective_from" date default CURRENT_DATE not null,
  "created_at" timestamptz default now() not null,
  "accrual_method" text default 'annual'::text not null
);

create table public."leave_types" (
  "id" uuid default uuid_generate_v4() not null,
  "is_deductible" boolean default true,
  "is_continuous" boolean default false,
  "max_days" integer,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "tenant_id" uuid,
  "name" text not null,
  "description" text,
  "icon" text
);

create table public."loan_payments" (
  "payment_id" bigint generated by default as identity not null,
  "loan_id" uuid,
  "amount_paid" numeric,
  "payment_date" date default CURRENT_DATE,
  "branch_id" bigint,
  "is_on_time" boolean,
  "principal_amount" numeric,
  "interest_amount" numeric,
  "fees_amount" numeric,
  "penalty_amount" numeric,
  "created_at" timestamptz default now(),
  "payment_method" text,
  "received_by" text
);

create table public."loan_requests" (
  "id" uuid default uuid_generate_v4() not null,
  "Basic Salary" numeric,
  "Loan Amount" numeric,
  "Number of Months" integer,
  "Monthly Deduction" numeric,
  "time_added" timestamptz default now(),
  "Employee Number" text,
  "Full Name" text,
  "Office Branch" text,
  "Repayment Schedule" text,
  "Reason for Loan" text,
  "status" text default 'Pending'::text,
  "admin_notes" text
);

create table public."loans" (
  "loan_id" uuid default uuid_generate_v4() not null,
  "branch_id" bigint,
  "amount_disbursed" numeric,
  "outstanding_balance" numeric,
  "interest_rate" numeric,
  "term_months" integer,
  "disbursement_date" date,
  "maturity_date" date,
  "par_days" integer default 0,
  "last_payment_date" date,
  "next_payment_date" date,
  "created_at" timestamptz default now(),
  "client_id" text,
  "loan_officer" text,
  "product_type" text,
  "repayment_frequency" text,
  "status" text default 'Pending'::text
);

create table public."meeting_transcripts" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "meeting_code" text,
  "participant_name" text,
  "transcript" text,
  "summary" text
);

create table public."message_reactions" (
  "message_id" uuid,
  "id" uuid default uuid_generate_v4() not null,
  "user_id" uuid,
  "created_at" timestamptz default now(),
  "emoji" text
);

create table public."messages" (
  "reactions" jsonb default '[]'::jsonb,
  "channel_id" uuid,
  "id" uuid default uuid_generate_v4() not null,
  "author_id" uuid,
  "mentions" jsonb default '[]'::jsonb,
  "attachments" jsonb default '[]'::jsonb,
  "reply_to" uuid,
  "is_edited" boolean default false,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "author_name" text,
  "author_initials" text,
  "author_avatar" text,
  "author_town" text,
  "content" text
);

create table public."mfa_codes" (
  "id" uuid default uuid_generate_v4() not null,
  "expires_at" timestamptz not null,
  "used" boolean default false,
  "created_at" timestamptz default now(),
  "email" text not null,
  "code" text not null,
  "phone_number" text not null
);

create table public."mfa_numbers" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "email" text not null,
  "phone_number" text not null
);

create table public."mpesa_callbacks" (
  "id" uuid default uuid_generate_v4() not null,
  "result_code" integer,
  "amount" numeric,
  "raw_response" jsonb,
  "callback_date" timestamptz default now(),
  "processed_at" timestamptz,
  "created_at" timestamptz default now(),
  "full_name" text,
  "transaction_id" text,
  "employee_number" text,
  "employee_id" text,
  "phone_number" text,
  "result_type" text,
  "result_desc" text,
  "status" text default 'Pending'::text,
  "originator_conversation_id" text,
  "conversation_id" text
);

create table public."mpesa_transactions" (
  "id" uuid default uuid_generate_v4() not null,
  "transaction_date" date,
  "amount" numeric,
  "created_at" timestamptz default now(),
  "loan_id" text,
  "transaction_time" text,
  "mpesa_code" text,
  "phone_number" text,
  "status" text default 'Pending'::text,
  "purpose" text
);

create table public."notifications" (
  "id" uuid default uuid_generate_v4() not null,
  "is_read" boolean default false,
  "created_at" timestamptz default now(),
  "title" text,
  "message" text,
  "type" text,
  "priority" text default 'medium'::text,
  "employee_number" text,
  "related_entity" text,
  "related_entity_id" text
);

create table public."payment_flows" (
  "id" uuid default uuid_generate_v4() not null,
  "employee_data" jsonb,
  "employees_data" jsonb,
  "total_amount" numeric,
  "created_by" uuid,
  "created_at" timestamptz default now(),
  "approved_by" uuid,
  "approved_at" timestamptz,
  "processed_by" uuid,
  "processed_at" timestamptz,
  "metadata" jsonb,
  "rejected_by" uuid,
  "rejected_at" timestamptz,
  "type" text default 'single'::text,
  "justification" text,
  "status" text default 'pending'::text,
  "approval_comment" text,
  "rejection_reason" text
);

create table public."payroll_records" (
  "created_at" timestamptz default now(),
  "id" bigint generated by default as identity not null,
  "Employee ID" text,
  "Employee Name" text,
  "Department" text,
  "Position" text,
  "Basic Salary" text,
  "House Allowance" text,
  "Transport Allowance" text,
  "Medical Allowance" text,
  "PAYE Tax" text,
  "Net Pay" text,
  "NHIF" text,
  "NSSF" text,
  "Total Deductions" text,
  "Housing Levy" text,
  "Overtime Hours" text,
  "Pay Period" text,
  "Overtime Pay" text,
  "Gross Pay" text,
  "employee_id" text,
  "pay_period" text
);

create table public."payroll_records_current" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "Employee ID" text,
  "Employee Name" text,
  "Department" text,
  "Position" text,
  "Basic Salary" text,
  "House Allowance" text,
  "Transport Allowance" text,
  "Branch" text,
  "Job Group" text,
  "Pay Period" text,
  "employee_id" text,
  "pay_period" text
);

create table public."performance_targets" (
  "id" bigint generated by default as identity not null,
  "branch_id" bigint,
  "target_value" numeric,
  "start_date" date,
  "end_date" date,
  "is_active" boolean default true,
  "created_at" timestamptz default now(),
  "target_for" text,
  "target_type" text,
  "employee_id" text,
  "product_type" text,
  "period" text
);

create table public."permissions" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "module_id" varchar not null,
  "module_name" varchar not null,
  "description" text,
  "category" varchar not null
);

create table public."phone_number_change_requests" (
  "id" uuid default uuid_generate_v4() not null,
  "requested_at" timestamptz default now(),
  "reviewed_at" timestamptz,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "employee_number" text not null,
  "current_phone" text,
  "requested_phone" text not null,
  "reason" text,
  "status" text default 'pending'::text not null,
  "reviewed_by" text,
  "admin_notes" text
);

create table public."profiles" (
  "id" uuid not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "display_name" text,
  "full_name" text,
  "avatar_url" text,
  "email" text,
  "role" text default 'STAFF'::text
);

create table public."regional_managers" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "employee_number" text,
  "full_name" text,
  "email" text,
  "region" text,
  "branch" text
);

create table public."role_permissions" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "role_name" text,
  "permissions" text[]
);

create table public."salary_advance" (
  "id" uuid default uuid_generate_v4() not null,
  "Amount Requested" numeric,
  "time_added" timestamptz default now(),
  "last_updated" timestamptz default now(),
  "admin_approval_date" timestamptz,
  "admin_adjusted_amount" numeric,
  "admin_rejection_date" timestamptz,
  "branch_manager_approval" boolean default false,
  "branch_manager_approval_date" timestamptz,
  "branch_manager_adjusted_amount" numeric,
  "regional_manager_comment_date" timestamptz,
  "regional_manager_approval" boolean default false,
  "regional_manager_approval_date" timestamptz,
  "regional_manager_adjusted_amount" numeric,
  "payment_date" timestamptz,
  "Employee Number" text,
  "Full Name" text,
  "Office Branch" text,
  "Basic Salary" text,
  "Net Salary" text,
  "Reason for Advance" text,
  "Region" text,
  "Town" text,
  "status" text default 'Pending'::text,
  "admin_notes" text,
  "admin_approval" text,
  "approved_by" text,
  "approved_by_email" text,
  "rejected_by" text,
  "rejected_by_email" text,
  "branch_manager_recommendation" text,
  "branch_manager_notes" text,
  "regional_manager_recommendation" text,
  "regional_manager_notes" text,
  "regional_manager_comment" text,
  "payment_processed" text default 'false'::text,
  "mpesa_transaction_id" text,
  "mpesa_result_desc" text,
  "mpesa_conversation_id" text
);

create table public."salary_advance_payment_flows" (
  "id" uuid default uuid_generate_v4() not null,
  "advances_data" jsonb default '[]'::jsonb,
  "total_amount" numeric,
  "created_by" uuid,
  "approved_by" uuid,
  "approved_at" timestamptz,
  "processed_at" timestamptz,
  "metadata" jsonb,
  "rejected_by" uuid,
  "rejected_at" timestamptz,
  "created_at" timestamptz default now(),
  "type" text default 'bulk'::text,
  "justification" text,
  "created_by_email" text,
  "status" text default 'pending'::text,
  "approved_by_email" text,
  "rejection_reason" text,
  "rejected_by_email" text
);

create table public."salary_advance_settings" (
  "id" integer default 1 not null,
  "applications_active" boolean default true,
  "closed_until" timestamptz,
  "closed_at" timestamptz,
  "reopened_at" timestamptz,
  "scheduled_close" timestamptz,
  "scheduled_open" timestamptz,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "closed_by" text,
  "schedule_type" text default 'manual'::text,
  "custom_message" text
);

create table public."salary_history" (
  "id" uuid default uuid_generate_v4() not null,
  "basic_salary" numeric,
  "gross_pay" numeric,
  "net_pay" numeric,
  "total_deductions" numeric,
  "nssf_deduction" numeric,
  "nhif_deduction" numeric,
  "paye_tax" numeric,
  "housing_levy" numeric,
  "house_allowance" numeric,
  "transport_allowance" numeric,
  "medical_allowance" numeric,
  "other_allowances" numeric,
  "overtime_hours" numeric,
  "overtime_rate" numeric,
  "commission" numeric,
  "bonus" numeric,
  "per_diem" numeric,
  "tax_relief" numeric,
  "loan_deduction" numeric,
  "advance_deduction" numeric,
  "welfare_deduction" numeric,
  "other_deductions" numeric,
  "created_at" timestamptz default now(),
  "employee_id" text,
  "employee_name" text,
  "pay_period" text,
  "payment_method" text,
  "bank_name" text,
  "account_number" text
);

create table public."sender_id_configs" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "user_id" text,
  "sender_id_type" text default 'default'::text,
  "custom_sender_id" text,
  "business_certificate_url" text,
  "consent_letter_url" text,
  "provider" text default 'safaricom'::text,
  "status" text default 'pending'::text
);

create table public."sms_logs" (
  "id" uuid default uuid_generate_v4() not null,
  "cost" numeric,
  "created_at" timestamptz default now(),
  "message" text,
  "recipient_phone" text,
  "status" text default 'sent'::text,
  "error_message" text,
  "message_id" text,
  "sender_id" text,
  "sms_type" text
);

create table public."sms_templates" (
  "id" uuid default uuid_generate_v4() not null,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "name" text,
  "category" text,
  "content" text,
  "variables" text[]
);

create table public."staff_loans" (
  "id" uuid default uuid_generate_v4() not null,
  "application_date" date,
  "loan_amount" numeric,
  "approved_amount" numeric,
  "interest_rate" numeric,
  "repayment_period" integer,
  "approval_date" date,
  "disbursement_date" date,
  "monthly_deduction" numeric,
  "total_repayable" numeric,
  "amount_deducted" numeric default 0,
  "amount_remaining" numeric,
  "last_deduction_date" date,
  "next_deduction_date" date,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "employee_number" text,
  "loan_type" text,
  "application_time" text,
  "purpose" text,
  "status" text default 'Pending'::text,
  "approved_by" text,
  "approval_time" text,
  "disbursement_time" text,
  "disbursement_method" text,
  "bank_account" text,
  "bank_name" text,
  "cheque_number" text,
  "mpesa_code" text,
  "deduction_status" text default 'Active'::text,
  "security_details" text,
  "guarantor1_name" text,
  "guarantor1_employee_number" text,
  "guarantor2_name" text,
  "guarantor2_employee_number" text,
  "remarks" text
);

create table public."staff_signup_requests" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamptz default now(),
  "email" text,
  "branch" text,
  "status" text default 'pending'::text
);

create table public."statutory_deductions" (
  "id" uuid default uuid_generate_v4() not null,
  "nssf_employee_contribution" numeric,
  "nssf_employer_contribution" numeric,
  "nssf_total_contribution" numeric,
  "nhif_amount" numeric,
  "nhif_dependents" integer,
  "paye_amount" numeric,
  "personal_relief" numeric,
  "insurance_relief" numeric,
  "taxable_income" numeric,
  "ahl_employee_contribution" numeric,
  "ahl_employer_contribution" numeric,
  "ahl_total_contribution" numeric,
  "nita_amount" numeric,
  "nita_training_levy" numeric,
  "total_statutory_deductions" numeric,
  "processed_date" date,
  "submitted_date" date,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "employee_number" text,
  "deduction_type" text,
  "deduction_period" text,
  "nssf_number" text,
  "nssf_tier" text,
  "nhif_number" text,
  "nhif_tier" text,
  "tax_band" text,
  "ahl_number" text,
  "nita_number" text,
  "status" text default 'Pending'::text,
  "remarks" text
);

create table public."statutory_settings" (
  "id" uuid default uuid_generate_v4() not null,
  "settings" jsonb,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "created_by" text
);

create table public."system_settings" (
  "id" integer default 1 not null,
  "gmail_token_expiry" timestamptz,
  "mfa_enabled" boolean default false,
  "updated_at" timestamptz default now(),
  "gmail_access_token" text,
  "gmail_refresh_token" text
);

create table public."termination_requests" (
  "id" uuid default uuid_generate_v4() not null,
  "termination_date" date,
  "requested_by" uuid,
  "approved_by" uuid,
  "rejected_by" uuid,
  "reversed_by" uuid,
  "approved_at" timestamptz,
  "rejected_at" timestamptz,
  "reversed_at" timestamptz,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "Employee Number" text,
  "employee_id" text,
  "employee_name" text,
  "employee_email" text,
  "employee_position" text,
  "status" text default 'pending'::text,
  "termination_reason" text,
  "exit_interview" text
);

create table public."todos" (
  "id" uuid default uuid_generate_v4() not null,
  "user_id" uuid,
  "completed" boolean default false,
  "due_date" timestamptz,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "assigne" uuid,
  "important" boolean default false,
  "completed_at" timestamptz,
  "requires_approval" boolean default false,
  "approved_by" uuid,
  "approved_at" timestamptz,
  "actual_time_spent" integer,
  "timer_started_at" timestamptz,
  "timer_running" boolean default false,
  "is_private" boolean default false,
  "loan_amount" numeric,
  "title" text,
  "description" text,
  "priority" text default 'medium'::text,
  "assigned_to" text,
  "branch" text,
  "department" text,
  "county" text,
  "status" text default 'not-started'::text,
  "category" text,
  "repeat" text default 'none'::text,
  "repeat_pattern" text,
  "completed_comment" text,
  "tags" text,
  "progress" text,
  "time_estimate" text,
  "loan_stage" text,
  "loan_reference" text,
  "client_name" text
);

create table public."training_documents" (
  "id" uuid default uuid_generate_v4() not null,
  "file_size" bigint,
  "required" boolean default false,
  "order" integer default 0,
  "quiz_required" boolean default false,
  "created_at" timestamptz default now(),
  "title" text,
  "description" text,
  "url" text,
  "file_name" text,
  "file_type" text,
  "category" text
);

create table public."training_progress" (
  "id" bigint generated by default as identity not null,
  "completed" boolean default false,
  "completed_at" timestamptz,
  "time_spent" integer default 0,
  "last_accessed" timestamptz default now(),
  "updated_at" timestamptz default now(),
  "quiz_passed" boolean,
  "quiz_score" integer,
  "document_id" text,
  "employee_number" text
);

create table public."training_videos" (
  "id" uuid default uuid_generate_v4() not null,
  "duration" bigint,
  "required" boolean default false,
  "order" smallint default 0,
  "quiz_required" boolean default false,
  "created_at" timestamptz default now(),
  "title" text,
  "description" text,
  "url" text,
  "category" text,
  "thumbnail_url" text
);

create table public."user_channel_states" (
  "user_id" uuid not null,
  "channel_id" uuid not null,
  "last_read_at" timestamptz default now()
);

create table public."user_profiles" (
  "user_id" uuid not null,
  "created_at" timestamptz default now(),
  "account_status" text default 'ACTIVE'::text,
  "full_name" text,
  "email" text,
  "role" text default 'STAFF'::text,
  "department" text
);

create table public."warnings" (
  "id" bigint generated by default as identity not null,
  "issued_at" date default CURRENT_DATE,
  "created_at" timestamptz default now(),
  "employee_id" text,
  "type" text,
  "severity" text,
  "message" text
);

alter table public."hr_contract_settings" add constraint "hr_contract_settings_pkey" PRIMARY KEY (id);

alter table public."assets" add constraint "assets_pkey" PRIMARY KEY (id);

alter table public."attendance_logs" add constraint "attendance_logs_pkey" PRIMARY KEY (id);

alter table public."audit_log" add constraint "audit_log_pkey" PRIMARY KEY (id);

alter table public."kenya_branches" add constraint "kenya_branches_pkey" PRIMARY KEY (id);

alter table public."kenya_branches_duplicate" add constraint "kenya_branches_duplicate_pkey" PRIMARY KEY (id);

alter table public."branch_performance" add constraint "branch_performance_pkey" PRIMARY KEY (id);

alter table public."channels" add constraint "channels_pkey" PRIMARY KEY (id);

alter table public."channel_members" add constraint "channel_members_pkey" PRIMARY KEY (id);

alter table public."messages" add constraint "messages_pkey" PRIMARY KEY (id);

alter table public."message_reactions" add constraint "message_reactions_pkey" PRIMARY KEY (id);

alter table public."employees" add constraint "employees_pkey" PRIMARY KEY ("Employee Number");

alter table public."leave_application" add constraint "leave_application_pkey" PRIMARY KEY (id);

alter table public."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY (user_id);

alter table public."mfa_numbers" add constraint "mfa_numbers_pkey" PRIMARY KEY (id);

alter table public."mfa_codes" add constraint "mfa_codes_pkey" PRIMARY KEY (id);

alter table public."company_logo" add constraint "company_logo_pkey" PRIMARY KEY (id);

alter table public."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY (id);

alter table public."hr_notifications" add constraint "hr_notifications_pkey" PRIMARY KEY (id);

alter table public."permissions" add constraint "permissions_pkey" PRIMARY KEY (id);

alter table public."hr_employment_status" add constraint "hr_employment_status_pkey" PRIMARY KEY (id);

alter table public."hr_lifecycle_history" add constraint "hr_lifecycle_history_pkey" PRIMARY KEY (id);

alter table public."hr_suspensions" add constraint "hr_suspensions_pkey" PRIMARY KEY (id);

alter table public."hr_terminations" add constraint "hr_terminations_pkey" PRIMARY KEY (id);

alter table public."hr_termination_interviews" add constraint "hr_termination_interviews_pkey" PRIMARY KEY (id);

alter table public."hr_salary_advances" add constraint "hr_salary_advances_pkey" PRIMARY KEY (id);

alter table public."hr_leave_schedules" add constraint "hr_leave_schedules_pkey" PRIMARY KEY (id);

alter table public."incident_reports" add constraint "incident_reports_pkey" PRIMARY KEY (id);

alter table public."job_postings" add constraint "job_postings_pkey" PRIMARY KEY (id);

alter table public."job_applications" add constraint "job_applications_pkey" PRIMARY KEY (id);

alter table public."job_positions" add constraint "job_positions_pkey" PRIMARY KEY (id);

alter table public."phone_number_change_requests" add constraint "phone_number_change_requests_pkey" PRIMARY KEY (id);

alter table public."dependents" add constraint "dependents_pkey" PRIMARY KEY (id);

alter table public."emergency_contact" add constraint "emergency_contact_pkey" PRIMARY KEY (id);

alter table public."employee_performance" add constraint "employee_performance_pkey" PRIMARY KEY (id);

alter table public."warnings" add constraint "warnings_pkey" PRIMARY KEY (id);

alter table public."training_documents" add constraint "training_documents_pkey" PRIMARY KEY (id);

alter table public."training_videos" add constraint "training_videos_pkey" PRIMARY KEY (id);

alter table public."training_progress" add constraint "training_progress_pkey" PRIMARY KEY (id);

alter table public."performance_targets" add constraint "performance_targets_pkey" PRIMARY KEY (id);

alter table public."clients" add constraint "clients_pkey" PRIMARY KEY (client_id);

alter table public."client_visits" add constraint "client_visits_pkey" PRIMARY KEY (visit_id);

alter table public."regional_managers" add constraint "regional_managers_pkey" PRIMARY KEY (id);

alter table public."meeting_transcripts" add constraint "meeting_transcripts_pkey" PRIMARY KEY (id);

alter table public."kenya_office_locations" add constraint "kenya_office_locations_pkey" PRIMARY KEY (id);

alter table public."todos" add constraint "todos_pkey" PRIMARY KEY (id);

alter table public."payroll_records" add constraint "payroll_records_pkey" PRIMARY KEY (id);

alter table public."payroll_records_current" add constraint "payroll_records_current_pkey" PRIMARY KEY (id);

alter table public."salary_history" add constraint "salary_history_pkey" PRIMARY KEY (id);

alter table public."salary_advance" add constraint "salary_advance_pkey" PRIMARY KEY (id);

alter table public."salary_advance_payment_flows" add constraint "salary_advance_payment_flows_pkey" PRIMARY KEY (id);

alter table public."salary_advance_settings" add constraint "salary_advance_settings_pkey" PRIMARY KEY (id);

alter table public."loans" add constraint "loans_pkey" PRIMARY KEY (loan_id);

alter table public."loan_payments" add constraint "loan_payments_pkey" PRIMARY KEY (payment_id);

alter table public."loan_requests" add constraint "loan_requests_pkey" PRIMARY KEY (id);

alter table public."staff_loans" add constraint "staff_loans_pkey" PRIMARY KEY (id);

alter table public."statutory_deductions" add constraint "statutory_deductions_pkey" PRIMARY KEY (id);

alter table public."statutory_settings" add constraint "statutory_settings_pkey" PRIMARY KEY (id);

alter table public."payment_flows" add constraint "payment_flows_pkey" PRIMARY KEY (id);

alter table public."expenses" add constraint "expenses_pkey" PRIMARY KEY (id);

alter table public."email_logs" add constraint "email_logs_pkey" PRIMARY KEY (id);

alter table public."holidays" add constraint "holidays_pkey" PRIMARY KEY (id);

alter table public."leave_types" add constraint "leave_types_pkey" PRIMARY KEY (id);

alter table public."mpesa_callbacks" add constraint "mpesa_callbacks_pkey" PRIMARY KEY (id);

alter table public."mpesa_transactions" add constraint "mpesa_transactions_pkey" PRIMARY KEY (id);

alter table public."notifications" add constraint "notifications_pkey" PRIMARY KEY (id);

alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);

alter table public."staff_signup_requests" add constraint "staff_signup_requests_pkey" PRIMARY KEY (id);

alter table public."system_settings" add constraint "system_settings_pkey" PRIMARY KEY (id);

alter table public."termination_requests" add constraint "termination_requests_pkey" PRIMARY KEY (id);

alter table public."user_channel_states" add constraint "user_channel_states_pkey" PRIMARY KEY (user_id, channel_id);

alter table public."sender_id_configs" add constraint "sender_id_configs_pkey" PRIMARY KEY (id);

alter table public."sms_logs" add constraint "sms_logs_pkey" PRIMARY KEY (id);

alter table public."sms_templates" add constraint "sms_templates_pkey" PRIMARY KEY (id);

alter table public."company_events" add constraint "company_events_pkey" PRIMARY KEY (id);

alter table public."leave_policies" add constraint "leave_policies_pkey" PRIMARY KEY (id);

alter table public."leave_balances" add constraint "leave_balances_pkey" PRIMARY KEY (id);

alter table public."leave_balance_adjustments" add constraint "leave_balance_adjustments_pkey" PRIMARY KEY (id);

alter table public."employees" add constraint "employees_Work Email_key" UNIQUE ("Work Email");

alter table public."user_profiles" add constraint "user_profiles_email_key" UNIQUE (email);

alter table public."mfa_numbers" add constraint "mfa_numbers_email_key" UNIQUE (email);

alter table public."role_permissions" add constraint "role_permissions_role_name_key" UNIQUE (role_name);

alter table public."permissions" add constraint "permissions_module_id_key" UNIQUE (module_id);

alter table public."training_progress" add constraint "training_progress_document_id_employee_number_key" UNIQUE (document_id, employee_number);

alter table public."emergency_contact" add constraint "emergency_contact_Employee Number_key" UNIQUE ("Employee Number");

alter table public."regional_managers" add constraint "regional_managers_email_key" UNIQUE (email);

alter table public."salary_history" add constraint "salary_history_employee_id_pay_period_key" UNIQUE (employee_id, pay_period);

alter table public."mpesa_callbacks" add constraint "mpesa_callbacks_originator_conversation_id_key" UNIQUE (originator_conversation_id);

alter table public."leave_policies" add constraint "leave_policies_leave_type_id_effective_from_key" UNIQUE (leave_type_id, effective_from);

alter table public."leave_balances" add constraint "leave_balances_unique_bucket" UNIQUE (employee_number, leave_type_id, year, month);

alter table public."hr_employment_status" add constraint "hr_employment_status_employment_type_check" CHECK ((employment_type = ANY (ARRAY['Attachment'::text, 'Probation'::text, 'Contract'::text, 'Permanent'::text])));

alter table public."hr_lifecycle_history" add constraint "hr_lifecycle_history_event_type_check" CHECK ((event_type = ANY (ARRAY['branch_transfer'::text, 'promotion'::text, 'position_change'::text, 'salary_revision'::text, 'status_change'::text, 'probation_confirmed'::text, 'probation_extended'::text, 'contract_renewed'::text, 'contract_converted'::text, 'suspension'::text, 'reactivation'::text, 'termination'::text, 'other'::text])));

alter table public."hr_terminations" add constraint "hr_terminations_termination_type_check" CHECK ((termination_type = ANY (ARRAY['Voluntary'::text, 'Dismissal'::text, 'Contract End'::text, 'Redundancy'::text])));

alter table public."hr_leave_schedules" add constraint "hr_leave_schedules_status_check" CHECK ((status = ANY (ARRAY['Scheduled'::text, 'Approved'::text, 'Rejected'::text, 'Completed'::text])));

alter table public."incident_reports" add constraint "incident_reports_incident_type_check" CHECK ((incident_type = ANY (ARRAY['harassment'::text, 'discrimination'::text, 'safety_violation'::text, 'ethics_violation'::text, 'fraud'::text, 'theft'::text, 'policy_violation'::text, 'workplace_violence'::text, 'other'::text])));

alter table public."incident_reports" add constraint "incident_reports_severity_check" CHECK ((severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])));

alter table public."incident_reports" add constraint "incident_reports_status_check" CHECK ((status = ANY (ARRAY['new'::text, 'under_review'::text, 'investigating'::text, 'resolved'::text, 'closed'::text, 'dismissed'::text])));

alter table public."phone_number_change_requests" add constraint "phone_number_change_requests_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));

alter table public."performance_targets" add constraint "performance_targets_target_for_check" CHECK ((target_for = ANY (ARRAY['employee'::text, 'branch'::text, 'product'::text])));

alter table public."leave_policies" add constraint "leave_policies_accrual_method_check" CHECK ((accrual_method = ANY (ARRAY['annual'::text, 'monthly_non_cumulative'::text, 'none'::text])));

alter table public."leave_balance_adjustments" add constraint "leave_balance_adjustments_change_type_check" CHECK ((change_type = ANY (ARRAY['approval_deduction'::text, 'annual_reset'::text, 'monthly_reset'::text])));

alter table public."hr_notifications" add constraint "hr_notifications_notification_type_check" CHECK ((notification_type = ANY (ARRAY['contract_expiring'::text, 'probation_expiring'::text, 'leave_recommended'::text, 'leave_approved'::text, 'leave_rejected'::text])));

alter table public."branch_performance" add constraint "branch_performance_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id);

alter table public."channel_members" add constraint "channel_members_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE;

alter table public."messages" add constraint "messages_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE;

alter table public."message_reactions" add constraint "message_reactions_message_id_fkey" FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

alter table public."leave_application" add constraint "leave_application_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number");

alter table public."hr_employment_status" add constraint "hr_employment_status_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_lifecycle_history" add constraint "hr_lifecycle_history_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_suspensions" add constraint "hr_suspensions_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_terminations" add constraint "hr_terminations_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_termination_interviews" add constraint "hr_termination_interviews_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_salary_advances" add constraint "hr_salary_advances_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."hr_leave_schedules" add constraint "hr_leave_schedules_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."training_progress" add constraint "training_progress_employee_number_fkey" FOREIGN KEY (employee_number) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."job_applications" add constraint "job_applications_job_posting_id_fkey" FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE;

alter table public."dependents" add constraint "dependents_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."emergency_contact" add constraint "emergency_contact_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."employee_performance" add constraint "employee_performance_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."warnings" add constraint "warnings_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."performance_targets" add constraint "performance_targets_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."performance_targets" add constraint "performance_targets_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id) ON DELETE SET NULL;

alter table public."clients" add constraint "clients_loan_officer_fkey" FOREIGN KEY (loan_officer) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."clients" add constraint "clients_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id) ON DELETE SET NULL;

alter table public."client_visits" add constraint "client_visits_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."client_visits" add constraint "client_visits_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE;

alter table public."client_visits" add constraint "client_visits_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id) ON DELETE SET NULL;

alter table public."regional_managers" add constraint "regional_managers_employee_number_fkey" FOREIGN KEY (employee_number) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."salary_advance" add constraint "salary_advance_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."loans" add constraint "loans_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE SET NULL;

alter table public."loans" add constraint "loans_loan_officer_fkey" FOREIGN KEY (loan_officer) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."loans" add constraint "loans_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id) ON DELETE SET NULL;

alter table public."loan_payments" add constraint "loan_payments_loan_id_fkey" FOREIGN KEY (loan_id) REFERENCES loans(loan_id) ON DELETE CASCADE;

alter table public."loan_payments" add constraint "loan_payments_received_by_fkey" FOREIGN KEY (received_by) REFERENCES employees("Employee Number") ON DELETE SET NULL;

alter table public."loan_payments" add constraint "loan_payments_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES kenya_branches(id) ON DELETE SET NULL;

alter table public."loan_requests" add constraint "loan_requests_Employee Number_fkey" FOREIGN KEY ("Employee Number") REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."staff_loans" add constraint "staff_loans_employee_number_fkey" FOREIGN KEY (employee_number) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."statutory_deductions" add constraint "statutory_deductions_employee_number_fkey" FOREIGN KEY (employee_number) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."leave_policies" add constraint "leave_policies_leave_type_id_fkey" FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE CASCADE;

alter table public."leave_balances" add constraint "leave_balances_employee_number_fkey" FOREIGN KEY (employee_number) REFERENCES employees("Employee Number") ON DELETE CASCADE;

alter table public."leave_balances" add constraint "leave_balances_leave_type_id_fkey" FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE CASCADE;

alter table public."leave_balance_adjustments" add constraint "leave_balance_adjustments_leave_balance_id_fkey" FOREIGN KEY (leave_balance_id) REFERENCES leave_balances(id) ON DELETE CASCADE;

create UNIQUE index if not exists leave_types_name_no_tenant_idx ON public.leave_types USING btree (name) WHERE (tenant_id IS NULL);

create UNIQUE index if not exists leave_types_tenant_name_idx ON public.leave_types USING btree (tenant_id, name) WHERE (tenant_id IS NOT NULL);

create index if not exists leave_types_tenant_idx ON public.leave_types USING btree (tenant_id);

create index if not exists idx_permissions_category ON public.permissions USING btree (category);

create index if not exists idx_permissions_module_id ON public.permissions USING btree (module_id);

create index if not exists idx_role_permissions_role_name ON public.role_permissions USING btree (role_name);

create index if not exists hr_notifications_employee_number_idx ON public.hr_notifications USING btree (employee_number);

create index if not exists hr_notifications_type_idx ON public.hr_notifications USING btree (notification_type);

create index if not exists hr_notifications_created_at_idx ON public.hr_notifications USING btree (created_at DESC);

create index if not exists leave_policies_leave_type_idx ON public.leave_policies USING btree (leave_type_id);

create index if not exists leave_balance_adjustments_balance_idx ON public.leave_balance_adjustments USING btree (leave_balance_id);

create index if not exists company_events_date_idx ON public.company_events USING btree (date);

create index if not exists leave_balances_employee_idx ON public.leave_balances USING btree (employee_number);

create index if not exists leave_balances_leave_type_idx ON public.leave_balances USING btree (leave_type_id);

create index if not exists leave_balances_year_idx ON public.leave_balances USING btree (year);

create index if not exists leave_balances_year_month_idx ON public.leave_balances USING btree (year, month);

alter table public."Employee_Records_Duplicate" enable row level security;

alter table public."assets" enable row level security;

alter table public."attendance_logs" enable row level security;

alter table public."audit_log" enable row level security;

alter table public."branch_performance" enable row level security;

alter table public."channel_members" enable row level security;

alter table public."channels" enable row level security;

alter table public."client_visits" enable row level security;

alter table public."clients" enable row level security;

alter table public."company_events" enable row level security;

alter table public."company_logo" enable row level security;

alter table public."dependents" enable row level security;

alter table public."email_logs" enable row level security;

alter table public."emergency_contact" enable row level security;

alter table public."employee_performance" enable row level security;

alter table public."employees" enable row level security;

alter table public."expenses" enable row level security;

alter table public."holidays" enable row level security;

alter table public."hr_contract_settings" enable row level security;

alter table public."hr_employment_status" enable row level security;

alter table public."hr_leave_schedules" enable row level security;

alter table public."hr_lifecycle_history" enable row level security;

alter table public."hr_notifications" enable row level security;

alter table public."hr_salary_advances" enable row level security;

alter table public."hr_suspensions" enable row level security;

alter table public."hr_termination_interviews" enable row level security;

alter table public."hr_terminations" enable row level security;

alter table public."incident_reports" enable row level security;

alter table public."job_applications" enable row level security;

alter table public."job_positions" enable row level security;

alter table public."job_postings" enable row level security;

alter table public."kenya_branches" enable row level security;

alter table public."kenya_branches_duplicate" enable row level security;

alter table public."kenya_office_locations" enable row level security;

alter table public."leave_application" enable row level security;

alter table public."leave_balance_adjustments" enable row level security;

alter table public."leave_balances" enable row level security;

alter table public."leave_policies" enable row level security;

alter table public."leave_types" enable row level security;

alter table public."loan_payments" enable row level security;

alter table public."loan_requests" enable row level security;

alter table public."loans" enable row level security;

alter table public."meeting_transcripts" enable row level security;

alter table public."message_reactions" enable row level security;

alter table public."messages" enable row level security;

alter table public."mfa_codes" enable row level security;

alter table public."mfa_numbers" enable row level security;

alter table public."mpesa_callbacks" enable row level security;

alter table public."mpesa_transactions" enable row level security;

alter table public."notifications" enable row level security;

alter table public."payment_flows" enable row level security;

alter table public."payroll_records" enable row level security;

alter table public."payroll_records_current" enable row level security;

alter table public."performance_targets" enable row level security;

alter table public."permissions" enable row level security;

alter table public."phone_number_change_requests" enable row level security;

alter table public."profiles" enable row level security;

alter table public."regional_managers" enable row level security;

alter table public."role_permissions" enable row level security;

alter table public."salary_advance" enable row level security;

alter table public."salary_advance_payment_flows" enable row level security;

alter table public."salary_advance_settings" enable row level security;

alter table public."salary_history" enable row level security;

alter table public."sender_id_configs" enable row level security;

alter table public."sms_logs" enable row level security;

alter table public."sms_templates" enable row level security;

alter table public."staff_loans" enable row level security;

alter table public."staff_signup_requests" enable row level security;

alter table public."statutory_deductions" enable row level security;

alter table public."statutory_settings" enable row level security;

alter table public."system_settings" enable row level security;

alter table public."termination_requests" enable row level security;

alter table public."todos" enable row level security;

alter table public."training_documents" enable row level security;

alter table public."training_progress" enable row level security;

alter table public."training_videos" enable row level security;

alter table public."user_channel_states" enable row level security;

alter table public."user_profiles" enable row level security;

alter table public."warnings" enable row level security;

create policy "Enable all access for authenticated users" on public."payroll_records" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."payroll_records_current" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."salary_history" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."salary_advance" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."salary_advance_payment_flows" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."salary_advance_settings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."loans" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."loan_payments" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."loan_requests" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."staff_loans" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."statutory_deductions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."statutory_settings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."payment_flows" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."expenses" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."email_logs" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."holidays" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."leave_types" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."mpesa_callbacks" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."mpesa_transactions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."notifications" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."assets" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."attendance_logs" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."audit_log" as permissive for all to authenticated using (true) with check (true);

create policy "Only admins can modify permissions" on public."permissions" as permissive for all using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'ADMIN'::text));

create policy "Anyone can view permissions" on public."permissions" as permissive for select using (true);

create policy "Only admins can modify role permissions" on public."role_permissions" as permissive for all using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'ADMIN'::text));

create policy "Anyone can view role permissions" on public."role_permissions" as permissive for select using (true);

create policy "Enable all access for authenticated users" on public."role_permissions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_suspensions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_terminations" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."kenya_branches_duplicate" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."kenya_branches" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."branch_performance" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."channel_members" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."message_reactions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."leave_application" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."mfa_numbers" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."mfa_codes" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."company_logo" as permissive for all to authenticated using (true) with check (true);

create policy "Admin full access" on public."hr_notifications" as permissive for all using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_lifecycle_history" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."messages" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."channels" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."profiles" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."staff_signup_requests" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."system_settings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."termination_requests" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."user_channel_states" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."sender_id_configs" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."sms_logs" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_contract_settings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_employment_status" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."sms_templates" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."Employee_Records_Duplicate" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_termination_interviews" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_salary_advances" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."hr_leave_schedules" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."incident_reports" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."job_postings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."job_applications" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."job_positions" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."phone_number_change_requests" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."dependents" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."emergency_contact" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."employee_performance" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."warnings" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."training_documents" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."training_videos" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."training_progress" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."performance_targets" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."clients" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."client_visits" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."regional_managers" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."meeting_transcripts" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."leave_policies" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."kenya_office_locations" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."todos" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."leave_balance_adjustments" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."company_events" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."leave_balances" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."employees" as permissive for all to authenticated using (true) with check (true);

create policy "Enable all access for authenticated users" on public."user_profiles" as permissive for all to authenticated using (true) with check (true);

create view public."current_leave_policies" as SELECT DISTINCT ON (leave_type_id) id,
    leave_type_id,
    days_allotted,
    accrual_method,
    carry_forward_max_days,
    effective_from,
    created_at
   FROM leave_policies
  WHERE (effective_from <= CURRENT_DATE)
  ORDER BY leave_type_id, effective_from DESC;

create view public."users" as SELECT user_id AS id,
    email,
    full_name,
    role,
    department,
    account_status,
    created_at
   FROM user_profiles;

CREATE OR REPLACE FUNCTION public.get_user_permissions(user_id uuid)
 RETURNS text[]
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  user_role TEXT;
  user_permissions TEXT[];
BEGIN
  -- Get user's role from auth.users metadata
  SELECT raw_user_meta_data->>'role' INTO user_role
  FROM auth.users
  WHERE id = user_id;
  
  IF user_role IS NULL THEN
    RETURN ARRAY[]::TEXT[];
  END IF;
  
  -- Get role's permissions
  SELECT permissions INTO user_permissions
  FROM role_permissions
  WHERE role_name = user_role;
  
  RETURN COALESCE(user_permissions, ARRAY[]::TEXT[]);
END;
$function$;

CREATE OR REPLACE FUNCTION public.has_permission(user_id uuid, required_permission text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  user_role TEXT;
  user_permissions TEXT[];
BEGIN
  -- Get user's role from auth.users metadata
  SELECT raw_user_meta_data->>'role' INTO user_role
  FROM auth.users
  WHERE id = user_id;
  
  IF user_role IS NULL THEN
    RETURN FALSE;
  END IF;
  
  -- Get role's permissions
  SELECT permissions INTO user_permissions
  FROM role_permissions
  WHERE role_name = user_role;
  
  -- Check if permission exists in array
  RETURN required_permission = ANY(user_permissions);
END;
$function$;

CREATE OR REPLACE FUNCTION public.increment_leave_balance_used_days(p_employee_number text, p_leave_type_id uuid, p_year integer, p_days numeric, p_month integer DEFAULT 0)
 RETURNS leave_balances
 LANGUAGE plpgsql
AS $function$
declare
  v_before public.leave_balances;
  v_after  public.leave_balances;
begin
  select * into v_before
  from public.leave_balances
  where employee_number = p_employee_number
    and leave_type_id = p_leave_type_id
    and year = p_year
    and month = p_month;

  insert into public.leave_balances (employee_number, leave_type_id, year, month, accrued_days, used_days)
  values (
    p_employee_number,
    p_leave_type_id,
    p_year,
    p_month,
    coalesce((select days_allotted from public.current_leave_policies where leave_type_id = p_leave_type_id), 0),
    p_days
  )
  on conflict (employee_number, leave_type_id, year, month)
  do update set used_days = public.leave_balances.used_days + excluded.used_days,
                updated_at = now()
  returning * into v_after;

  insert into public.leave_balance_adjustments
    (leave_balance_id, change_type, delta_days, used_days_before, used_days_after, accrued_days_before, accrued_days_after, reason)
  values
    (v_after.id, 'approval_deduction', p_days,
     coalesce(v_before.used_days, 0), v_after.used_days,
     coalesce(v_before.accrued_days, v_after.accrued_days), v_after.accrued_days,
     'Leave application approved');

  return v_after;
end;
$function$;

CREATE OR REPLACE FUNCTION public.run_annual_leave_reset(p_year integer)
 RETURNS SETOF leave_balances
 LANGUAGE plpgsql
AS $function$
declare
  r record;
  v_carry numeric;
  v_new_row public.leave_balances;
begin
  for r in
    select
      e."Employee Number" as employee_number,
      lt.id as leave_type_id,
      cp.days_allotted,
      cp.carry_forward_max_days,
      prev.remaining_days as prev_remaining
    from public.employees e
    cross join public.leave_types lt
    join public.current_leave_policies cp on cp.leave_type_id = lt.id
    left join public.leave_balances prev
      on prev.employee_number = e."Employee Number"
     and prev.leave_type_id = lt.id
     and prev.year = p_year - 1
     and prev.month = 0
    where lt.is_deductible = true
      and cp.accrual_method = 'annual'
  loop
    v_carry := greatest(least(coalesce(r.prev_remaining, 0), r.carry_forward_max_days), 0);

    insert into public.leave_balances (employee_number, leave_type_id, year, month, accrued_days, used_days, carried_over_days)
    values (r.employee_number, r.leave_type_id, p_year, 0, coalesce(r.days_allotted, 0), 0, v_carry)
    on conflict (employee_number, leave_type_id, year, month) do nothing
    returning * into v_new_row;

    if found then
      insert into public.leave_balance_adjustments
        (leave_balance_id, change_type, delta_days, used_days_before, used_days_after, accrued_days_before, accrued_days_after, reason)
      values
        (v_new_row.id, 'annual_reset', coalesce(r.days_allotted, 0) + v_carry, 0, 0, 0, coalesce(r.days_allotted, 0),
         format('Annual reset for %s: %s days allotted + %s carried forward from %s', p_year, coalesce(r.days_allotted, 0), v_carry, p_year - 1));
      return next v_new_row;
    end if;
  end loop;
end;
$function$;

CREATE OR REPLACE FUNCTION public.run_monthly_leave_reset(p_year integer, p_month integer)
 RETURNS SETOF leave_balances
 LANGUAGE plpgsql
AS $function$
declare
  r record;
  v_new_row public.leave_balances;
begin
  for r in
    select
      e."Employee Number" as employee_number,
      lt.id as leave_type_id,
      cp.days_allotted
    from public.employees e
    cross join public.leave_types lt
    join public.current_leave_policies cp on cp.leave_type_id = lt.id
    where lt.is_deductible = true
      and cp.accrual_method = 'monthly_non_cumulative'
  loop
    insert into public.leave_balances (employee_number, leave_type_id, year, month, accrued_days, used_days, carried_over_days)
    values (r.employee_number, r.leave_type_id, p_year, p_month, coalesce(r.days_allotted, 0), 0, 0)
    on conflict (employee_number, leave_type_id, year, month) do nothing
    returning * into v_new_row;

    if found then
      insert into public.leave_balance_adjustments
        (leave_balance_id, change_type, delta_days, used_days_before, used_days_after, accrued_days_before, accrued_days_after, reason)
      values
        (v_new_row.id, 'monthly_reset', coalesce(r.days_allotted, 0), 0, 0, 0, coalesce(r.days_allotted, 0),
         format('Monthly reset for %s-%s: %s days, does not carry over', p_year, p_month, coalesce(r.days_allotted, 0)));
      return next v_new_row;
    end if;
  end loop;
end;
$function$;
