import { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import toast from 'react-hot-toast';
import { sendEmail } from '../../services/email';
import { Card, Button, SearchInput, StatusPill, EmptyState } from '../UI';
import {
  AlertTriangle,
  Mail,
  FileText,
  ChevronDown,
  ChevronUp,
  Plus,
  X,
  Loader2,
  Calendar,
  Building,
  BadgeAlert,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  Brain,
  Zap
} from 'lucide-react';

// Define the DeepSeekResponse interface
interface DeepSeekResponse {
  response: string;
  metadata?: any;
}

// AI query function
const queryDeepSeek = async (
  prompt: string,
  context: string
): Promise<DeepSeekResponse> => {
  const apiKey = import.meta.env.VITE_DEEPSEEK_API_KEY;

  if (!apiKey) {
    throw new Error('DeepSeek API key is not configured');
  }

  const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'deepseek-chat',
      messages: [
        {
          role: 'system',
          content: `You are an HR assistant. Analyze this HR data and respond helpfully: ${context}`
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || 'DeepSeek API request failed');
  }

  const data = await response.json();
  return {
    response: data.choices[0].message.content,
    metadata: data.usage
  };
};

export default function WarningModule() {
  const [employees, setEmployees] = useState<any[]>([]);
  const [warnings, setWarnings] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState('');
  const [warningType, setWarningType] = useState('');
  const [severity, setSeverity] = useState('medium');
  const [customMessage, setCustomMessage] = useState('');
  const [useCustomMessage, setUseCustomMessage] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [employeeSearchTerm, setEmployeeSearchTerm] = useState('');
  const [warningSearchTerm, setWarningSearchTerm] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [editingTemplate, setEditingTemplate] = useState(null);
  const [showEmployeeDropdown, setShowEmployeeDropdown] = useState(false);
  const [aiSpecificities, setAiSpecificities] = useState('');
  const [aiAutoGenerated, setAiAutoGenerated] = useState(false);


  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(5);

  // Predefined warning templates
  const [warningTemplates, setWarningTemplates] = useState([
    {
      id: 1,
      type: 'Tardiness',
      subject: 'Warning Regarding Frequent Tardiness',
      message: 'This is a formal warning regarding your frequent tardiness. Continued violations may result in further disciplinary action.'
    },
    {
      id: 2,
      type: 'Performance',
      subject: 'Warning Regarding Performance Issues',
      message: 'This is a formal warning regarding your recent performance which has not met the expected standards. We expect to see immediate improvement.'
    },
    {
      id: 3,
      type: 'Conduct',
      subject: 'Warning Regarding Unprofessional Conduct',
      message: 'This is a formal warning regarding your recent behavior which violates our code of conduct. Further incidents may lead to disciplinary action.'
    },
    {
      id: 4,
      type: 'Policy Violation',
      subject: 'Warning Regarding Policy Violation',
      message: 'This is a formal warning regarding your violation of company policy. Please review the employee handbook and ensure compliance moving forward.'
    }
  ]);

  useEffect(() => {
    fetchEmployees();
    fetchWarnings();
  }, []);

  const fetchEmployees = async () => {
    try {
      console.log('Fetching employees...');

      const { data, error } = await supabase
        .from('employees')
        .select('*')
        .order('"Employee Number"', { ascending: true });

      if (error) {
        console.error('Error fetching employees:', error);
        toast.error('Failed to load employees');
        return;
      }

      console.log('Raw employee data:', data);

      // Format employee data using the actual table column names
      const formattedEmployees = (data || []).map(emp => {
        const employeeNumber = emp['Employee Number'];
        const firstName = emp['First Name'] || '';
        const lastName = emp['Last Name'] || '';
        const middleName = emp['Middle Name'] || '';
        const email = emp['Work Email'] || '';
        const department = emp['Job Title'] || emp['Department'] || 'N/A';
        const town = emp['Town'] || emp['City'] || '';

        // Construct full name with proper handling of middle name
        let fullName = firstName;
        if (middleName) {
          fullName += ` ${middleName}`;
        }
        if (lastName) {
          fullName += ` ${lastName}`;
        }

        return {
          ...emp,
          employeeNumber,
          fullName: fullName.trim() || 'Unknown Employee',
          firstName,
          lastName,
          middleName,
          email,
          department,
          town
        };
      });

      console.log('Formatted employees:', formattedEmployees);
      setEmployees(formattedEmployees);
    } catch (error) {
      console.error('Error in fetchEmployees:', error);
      toast.error('Failed to load employees');
    }
  };

  const fetchWarnings = async () => {
    try {
      const { data: warningsData, error: warningsError } = await supabase
        .from("warnings")
        .select("*")
        .order("issued_at", { ascending: false });

      if (warningsError) throw warningsError;

      // Get all unique employee numbers from warnings
      const employeeNumbers = [...new Set(warningsData.map(w => w.employee_id))].filter(Boolean);

      // Fetch employee data for these employee numbers
      let employeesData = [];
      if (employeeNumbers.length > 0) {
        const { data: empData, error: empError } = await supabase
          .from('employees')
          .select('*')
          .in('"Employee Number"', employeeNumbers);

        if (empError) {
          console.error('Error fetching employee details:', empError);
        } else {
          employeesData = empData || [];
        }
      }

      // Combine warnings with employee data
      const formattedWarnings = (warningsData || []).map(warning => {
        const employee = employeesData.find(emp => emp['Employee Number'] === warning.employee_id);

        let fullName = 'Unknown Employee';
        let email = 'No email';
        let department = 'No department';

        if (employee) {
          const firstName = employee['First Name'] || '';
          const middleName = employee['Middle Name'] || '';
          const lastName = employee['Last Name'] || '';

          // Construct full name
          fullName = firstName;
          if (middleName) {
            fullName += ` ${middleName}`;
          }
          if (lastName) {
            fullName += ` ${lastName}`;
          }
          fullName = fullName.trim() || 'Unknown Employee';

          email = employee['Work Email'] || 'No email';
          department = employee['Job Title'] || employee['Department'] || 'No department';
        }

        return {
          ...warning,
          employeeData: {
            fullName,
            email,
            department,
            employeeNumber: warning.employee_id
          }
        };
      });

      setWarnings(formattedWarnings);
    } catch (error) {
      console.error("Error fetching warnings:", error);
      toast.error("Failed to load warnings");
    } finally {
      setLoading(false);
    }
  };

  const handleTemplateSelect = (template) => {
    setWarningType(template.type);
    setCustomMessage(template.message);
    setSelectedTemplate(template);
    setShowTemplates(false);
    setUseCustomMessage(false);
    setEditingTemplate(null);
    setAiAutoGenerated(false);
  };

  const handleEditTemplate = (template) => {
    setEditingTemplate({ ...template });
    setCustomMessage(template.message);
    setWarningType(template.type);
  };

  const handleSaveTemplateEdit = () => {
    if (!editingTemplate) return;

    const updatedTemplates = warningTemplates.map(t =>
      t.id === editingTemplate.id ? editingTemplate : t
    );

    setWarningTemplates(updatedTemplates);
    setCustomMessage(editingTemplate.message);
    setWarningType(editingTemplate.type);
    setSelectedTemplate(editingTemplate);
    setEditingTemplate(null);
    toast.success('Template updated');
  };

  const handleCancelTemplateEdit = () => {
    if (selectedTemplate) {
      setCustomMessage(selectedTemplate.message);
      setWarningType(selectedTemplate.type);
    }
    setEditingTemplate(null);
  };

  const generateAIMessageStandalone = async () => {
    if (!selectedEmployee || !aiSpecificities.trim()) {
      toast.error('Please select an employee and provide AI specificities');
      return;
    }

    setAiLoading(true);

    try {
      const employee = employees.find(emp => emp.employeeNumber === selectedEmployee);

      if (!employee) {
        throw new Error('Selected employee not found');
      }

      const context = `
        Employee: ${employee.fullName}
        Department: ${employee.department}
        Severity Level: ${severity}
        AI Specificities: ${aiSpecificities}
      `;

      const prompt = `Based on the following specificities, generate a professional HR warning message and suggest an appropriate warning type: "${aiSpecificities}". 

Please format your response as:
WARNING TYPE: [suggested type]
MESSAGE: [professional warning message]

Make sure to incorporate the severity level (${severity}) and be specific about the issues mentioned in the specificities.`;

      const aiResponse = await queryDeepSeek(prompt, context);

      // Parse AI response to extract type and message
      const responseLines = aiResponse.response.split('\n');
      let suggestedType = '';
      let generatedMessage = '';

      for (const line of responseLines) {
        if (line.startsWith('WARNING TYPE:')) {
          suggestedType = line.replace('WARNING TYPE:', '').trim();
        } else if (line.startsWith('MESSAGE:')) {
          generatedMessage = line.replace('MESSAGE:', '').trim();
        } else if (generatedMessage) {
          generatedMessage += '\n' + line;
        }
      }

      // If parsing failed, use the entire response as message
      if (!generatedMessage) {
        generatedMessage = aiResponse.response;
        suggestedType = 'AI Generated Warning';
      }

      setWarningType(suggestedType);
      setCustomMessage(generatedMessage.trim());
      setUseCustomMessage(true);
      setAiAutoGenerated(true);
      setSelectedTemplate(null); // Clear any selected template

      toast.success('AI message generated successfully!');
    } catch (error) {
      console.error('Error generating AI message:', error);
      toast.error(`Failed to generate message: ${error.message}`);
    } finally {
      setAiLoading(false);
    }
  };

  const generateAIMessage = async () => {
    if (!selectedEmployee || !warningType) {
      toast.error('Please select an employee and warning type first');
      return;
    }

    setAiLoading(true);

    try {
      const employee = employees.find(emp => emp.employeeNumber === selectedEmployee);

      if (!employee) {
        throw new Error('Selected employee not found');
      }

      const context = `
        Employee: ${employee.fullName}
        Department: ${employee.department}
        Warning Type: ${warningType}
        Severity: ${severity}
        ${aiSpecificities ? `Additional Requirements: ${aiSpecificities}` : ''}
      `;

      let prompt = `Generate a professional HR warning message for ${warningType} with ${severity} severity level.`;

      if (aiSpecificities.trim()) {
        prompt += ` Please incorporate these specific requirements: ${aiSpecificities}`;
      }

      const aiResponse = await queryDeepSeek(prompt, context);
      setCustomMessage(aiResponse.response);
      setUseCustomMessage(true);
      toast.success('AI message generated with your specificities');
    } catch (error) {
      console.error('Error generating AI message:', error);
      toast.error(`Failed to generate message: ${error.message}`);
    } finally {
      setAiLoading(false);
    }
  };

  const sendWarning = async (e) => {
    e.preventDefault();
    if (!selectedEmployee || (!warningType && !aiAutoGenerated)) {
      toast.error('Please select an employee and warning type');
      return;
    }

    setSending(true);

    try {
      const employee = employees.find(emp => emp.employeeNumber === selectedEmployee);

      if (!employee) {
        throw new Error('Selected employee not found');
      }

      // 1. Save warning to database
      const { error: warningError } = await supabase
        .from('warnings')
        .insert([
          {
            employee_id: selectedEmployee,
            type: warningType || 'AI Generated Warning',
            severity: severity,
            message: customMessage,
            issued_at: new Date().toISOString()
          }
        ])
        .select();

      if (warningError) throw warningError;

      // 2. Send email (if email exists)
      if (employee.email) {
        const subject = warningTemplates.find(t => t.type === warningType)?.subject || `Warning: ${warningType || 'AI Generated Warning'}`;

        const htmlContent = `
              <div style="font-family: 'Inter', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
                <h2 style="color: #dc2626; text-align: center;">Official Warning Notice</h2>
                
                <div style="background-color: #fef2f2; padding: 16px; border-radius: 8px; margin: 16px 0;">
                  <p style="font-weight: bold; margin-bottom: 8px;">Dear ${employee.fullName},</p>
                  <p>This is an official warning regarding: <strong>${warningType || 'AI Generated Warning'}</strong></p>
                  <p>Severity: <span style="color: ${severity === 'high' ? '#dc2626' : severity === 'medium' ? '#ea580c' : '#ca8a04'}">${severity}</span></p>
                </div>
                
                <div style="padding: 16px; border-left: 4px solid #fecaca; background-color: #fafafa; margin: 16px 0;">
                  <p style="font-style: italic;">${customMessage}</p>
                </div>
                
                <p style="font-size: 14px; color: #64748b;">Please take this warning seriously and address the issues mentioned above. Failure to improve may result in further disciplinary action.</p>
                
                <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
                  <p>Please do not reply to this email.</p>
                </div>
              </div>
            `;

        await sendEmail({
          to: employee.email,
          subject: subject,
          html: htmlContent
        });
      }

      toast.success(`Warning sent to ${employee.fullName}`);
      resetForm();
      fetchWarnings();
      setCurrentPage(1); // Reset to first page after adding a new warning
    } catch (error) {
      console.error('Error sending warning:', error);
      toast.error(`Failed to send warning: ${error.message}`);
    } finally {
      setSending(false);
    }
  };

  const resetForm = () => {
    setSelectedEmployee('');
    setWarningType('');
    setSeverity('medium');
    setCustomMessage('');
    setUseCustomMessage(false);
    setShowForm(false);
    setSelectedTemplate(null);
    setEditingTemplate(null);
    setAiSpecificities('');
    setAiAutoGenerated(false);
    setEmployeeSearchTerm('');
    setShowEmployeeDropdown(false);
  };

  // Filter warnings based on search term
  const filteredWarnings = warnings.filter(warning => {
    const searchLower = warningSearchTerm.toLowerCase();
    const employeeName = warning.employeeData?.fullName || '';
    const employeeEmail = warning.employeeData?.email || '';

    return (
      employeeName.toLowerCase().includes(searchLower) ||
      String(warning.employee_id || '').toLowerCase().includes(searchLower) ||
      employeeEmail.toLowerCase().includes(searchLower) ||
      warning.type?.toLowerCase().includes(searchLower) ||
      warning.message?.toLowerCase().includes(searchLower)
    );
  });

  // Pagination logic
  const totalPages = Math.ceil(filteredWarnings.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedWarnings = filteredWarnings.slice(startIndex, startIndex + itemsPerPage);

  const handlePageChange = (page) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  // Generate page numbers for pagination
  const getPageNumbers = () => {
    const pageNumbers = [];
    const maxVisiblePages = 5;

    if (totalPages <= maxVisiblePages) {
      // Show all pages if total pages is less than max visible
      for (let i = 1; i <= totalPages; i++) {
        pageNumbers.push(i);
      }
    } else {
      // Always include first page
      pageNumbers.push(1);

      // Calculate start and end of visible page range
      let startPage = Math.max(2, currentPage - 1);
      let endPage = Math.min(totalPages - 1, currentPage + 1);

      // Adjust if we're near the beginning
      if (currentPage <= 3) {
        endPage = 4;
      }

      // Adjust if we're near the end
      if (currentPage >= totalPages - 2) {
        startPage = totalPages - 3;
      }

      // Add ellipsis after first page if needed
      if (startPage > 2) {
        pageNumbers.push('...');
      }

      // Add middle pages
      for (let i = startPage; i <= endPage; i++) {
        pageNumbers.push(i);
      }

      // Add ellipsis before last page if needed
      if (endPage < totalPages - 1) {
        pageNumbers.push('...');
      }

      // Always include last page
      pageNumbers.push(totalPages);
    }

    return pageNumbers;
  };

  const inputClass =
    'w-full px-3 py-2 text-xs border border-border rounded-tile bg-white text-ink outline-none focus:border-brand transition-colors';

  const severityTone = (level) => {
    switch (level) {
      case 'low': return 'neutral';
      case 'medium': return 'warning';
      case 'high': return 'danger';
      default: return 'neutral';
    }
  };

  const thisMonthCount = warnings.filter(w => {
    const warningDate = new Date(w.issued_at);
    const now = new Date();
    return warningDate.getMonth() === now.getMonth() &&
      warningDate.getFullYear() === now.getFullYear();
  }).length;

  const statTiles = [
    { label: 'Total Warnings', value: warnings.length, icon: AlertTriangle, tint: 'bg-orange-tint-alt text-status-danger' },
    { label: 'High Severity', value: warnings.filter(w => w.severity === 'high').length, icon: BadgeAlert, tint: 'bg-orange-tint-alt text-status-danger' },
    { label: 'This Month', value: thisMonthCount, icon: Calendar, tint: 'bg-orange-tint text-orange-text' },
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="w-10 h-10 text-brand animate-spin" />
          <p className="m-0 text-xs text-muted-foreground font-medium">Loading warnings...</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <h1 className="m-0 text-[21px] font-bold text-ink">Warning Module</h1>
      <div className="text-[12.5px] text-muted-foreground mt-1 mb-[18px]">Issue formal warnings to employees</div>

      {/* Stat tiles */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5">
        {statTiles.map(({ label, value, icon: Icon, tint }) => (
          <Card key={label} className="flex items-center justify-between">
            <div>
              <div className="text-[10.5px] font-bold uppercase text-subtle">{label}</div>
              <div className="text-[22px] font-bold text-ink mt-1">{value}</div>
            </div>
            <div className={`w-[38px] h-[38px] rounded-tile flex items-center justify-center ${tint}`}>
              <Icon className="w-[17px] h-[17px]" strokeWidth={1.8} />
            </div>
          </Card>
        ))}
      </div>

      {/* Search + issue */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2.5 mb-[18px]">
        <div className="flex-1">
          <SearchInput
            placeholder="Search warnings..."
            value={warningSearchTerm}
            onChange={(e) => {
              setWarningSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
            className="!bg-white !border-border"
          />
        </div>
        <div className="flex items-center gap-2">
          <label htmlFor="itemsPerPage" className="text-xs text-muted-foreground">Show:</label>
          <select
            id="itemsPerPage"
            value={itemsPerPage}
            onChange={(e) => {
              setItemsPerPage(Number(e.target.value));
              setCurrentPage(1);
            }}
            className="border border-border bg-white rounded-tile px-2 py-1.5 text-xs text-ink outline-none focus:border-brand"
          >
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
          </select>
          <Button
            className="!bg-status-danger !border-status-danger hover:!opacity-90"
            onClick={() => setShowForm(!showForm)}
            icon={<Plus className="w-3.5 h-3.5" strokeWidth={2.2} />}
          >
            Issue Warning
          </Button>
        </div>
      </div>

      {/* Warning form */}
      {showForm && (
        <Card className="mb-5">
          <div className="flex items-center justify-between mb-5">
            <h2 className="m-0 text-[15px] font-bold text-ink">Issue New Warning</h2>
            <button
              type="button"
              aria-label="Close form"
              onClick={() => setShowForm(false)}
              className="text-subtle hover:text-ink transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <form onSubmit={sendWarning} className="space-y-5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div className="relative">
                <label htmlFor="warn-employee" className="block text-[11px] font-semibold text-ink mb-1.5">Select Employee</label>
                <input
                  id="warn-employee"
                  type="text"
                  autoComplete="off"
                  placeholder="Search employee by name, department or ID..."
                  value={employeeSearchTerm}
                  onChange={(e) => {
                    setEmployeeSearchTerm(e.target.value);
                    setShowEmployeeDropdown(true);
                  }}
                  onFocus={() => setShowEmployeeDropdown(true)}
                  className={inputClass}
                />

                {showEmployeeDropdown && employeeSearchTerm && (
                  <ul className="absolute z-10 w-full mt-1 p-0 list-none bg-white border border-border rounded-lg shadow-lg max-h-48 overflow-y-auto">
                    {employees
                      .filter((emp) => {
                        const search = employeeSearchTerm.toLowerCase();
                        return (
                          emp.fullName.toLowerCase().includes(search) ||
                          emp.department.toLowerCase().includes(search) ||
                          emp.employeeNumber.toString().toLowerCase().includes(search)
                        );
                      })
                      .map((emp) => (
                        <li key={emp.employeeNumber}>
                          <button
                            type="button"
                            onClick={() => {
                              const displayValue = `${emp.fullName} - ${emp.department} (ID: ${emp.employeeNumber})`;
                              setSelectedEmployee(emp.employeeNumber);
                              setEmployeeSearchTerm(displayValue);
                              setShowEmployeeDropdown(false);
                            }}
                            className="w-full text-left px-3 py-2 hover:bg-background text-xs text-ink"
                          >
                            {emp.fullName} - {emp.department} (ID: {emp.employeeNumber})
                          </button>
                        </li>
                      ))}
                  </ul>
                )}
              </div>

              <div className="relative">
                <span className="block text-[11px] font-semibold text-ink mb-1.5">Warning Type (Optional)</span>
                <button
                  type="button"
                  onClick={() => setShowTemplates(!showTemplates)}
                  aria-expanded={showTemplates}
                  className={`${inputClass} text-left flex items-center justify-between`}
                >
                  {warningType || 'Select a warning type (or use AI)'}
                  {showTemplates ? <ChevronUp className="w-4 h-4 text-subtle" /> : <ChevronDown className="w-4 h-4 text-subtle" />}
                </button>

                {showTemplates && (
                  <div className="absolute z-10 mt-1 w-full bg-white border border-border rounded-lg shadow-lg overflow-hidden">
                    {warningTemplates.map(template => (
                      <button
                        type="button"
                        key={template.id}
                        onClick={() => handleTemplateSelect(template)}
                        className="w-full text-left px-3 py-2.5 hover:bg-background border-b border-[#F1F5F2] last:border-b-0 transition-colors"
                      >
                        <div className="text-xs font-semibold text-ink">{template.type}</div>
                        <div className="text-[11px] text-muted-foreground truncate">{template.message.substring(0, 60)}...</div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            <fieldset className="m-0 p-0 border-0">
              <legend className="text-[11px] font-semibold text-ink mb-1.5 p-0">Severity Level</legend>
              <div className="flex gap-4">
                {['low', 'medium', 'high'].map(level => (
                  <label key={level} className="flex items-center gap-2 text-xs text-ink capitalize cursor-pointer">
                    <input
                      type="radio"
                      name="severity"
                      value={level}
                      checked={severity === level}
                      onChange={() => setSeverity(level)}
                      className="h-4 w-4 accent-[#17402A]"
                    />
                    {level}
                  </label>
                ))}
              </div>
            </fieldset>

            {/* AI section */}
            <div className="bg-background p-4 rounded-xl border border-border">
              <div className="flex items-center justify-between mb-3">
                <label htmlFor="warn-ai" className="flex items-center gap-2 text-xs font-semibold text-ink">
                  <Zap className="w-4 h-4 text-status-purple" />
                  Generate message using AI
                </label>
                <span className="flex items-center gap-1.5 bg-status-purple-tint px-2.5 py-1 rounded-pill text-[11px] font-semibold text-status-purple">
                  <Brain className="w-3.5 h-3.5" />
                  Smart AI
                </span>
              </div>

              <textarea
                id="warn-ai"
                value={aiSpecificities}
                onChange={(e) => setAiSpecificities(e.target.value)}
                rows={4}
                className={`${inputClass} resize-none`}
                placeholder="Describe the warning situation in detail. For example:
• 'Employee has been late 5 times this month, coming in 15-30 minutes after 9 AM'
• 'Poor performance on quarterly reports with multiple errors and missed deadlines'
• 'Inappropriate behavior during team meetings, interrupting colleagues'

The AI will determine the warning type and generate a professional message."
              />

              <div className="flex items-center justify-between mt-3">
                <p className="m-0 text-[11px] text-muted-foreground">
                  Describe the situation and the AI will draft the type and message.
                </p>
                <Button
                  onClick={generateAIMessageStandalone}
                  disabled={!selectedEmployee || !aiSpecificities.trim() || aiLoading}
                  icon={aiLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Zap className="w-3.5 h-3.5" />}
                >
                  {aiLoading ? 'Generating...' : 'Generate Warning'}
                </Button>
              </div>
            </div>

            {/* Template / custom message */}
            {!aiAutoGenerated && (
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="warn-message" className="text-[11px] font-semibold text-ink">Warning Message</label>
                  <div className="flex items-center gap-4">
                    <label className="flex items-center gap-2 text-xs text-ink cursor-pointer">
                      <input
                        type="checkbox"
                        checked={useCustomMessage}
                        onChange={() => setUseCustomMessage(!useCustomMessage)}
                        className="h-4 w-4 accent-[#17402A]"
                      />
                      Custom message
                    </label>
                    {warningType && (
                      <Button
                        variant="secondary"
                        onClick={generateAIMessage}
                        disabled={!selectedEmployee || !warningType || aiLoading}
                        icon={aiLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
                      >
                        AI Enhance
                      </Button>
                    )}
                  </div>
                </div>

                {editingTemplate ? (
                  <div className="space-y-3">
                    <input
                      type="text"
                      aria-label="Template type"
                      value={editingTemplate.type}
                      onChange={(e) => setEditingTemplate({ ...editingTemplate, type: e.target.value })}
                      className={inputClass}
                    />
                    <textarea
                      aria-label="Template message"
                      value={editingTemplate.message}
                      onChange={(e) => setEditingTemplate({ ...editingTemplate, message: e.target.value })}
                      rows={4}
                      className={inputClass}
                    />
                    <div className="flex justify-end gap-2">
                      <Button variant="secondary" onClick={handleCancelTemplateEdit}>Cancel</Button>
                      <Button onClick={handleSaveTemplateEdit}>Save Template</Button>
                    </div>
                  </div>
                ) : useCustomMessage ? (
                  <div className="space-y-2">
                    <textarea
                      id="warn-message"
                      value={customMessage}
                      onChange={(e) => setCustomMessage(e.target.value)}
                      rows={4}
                      className={inputClass}
                      placeholder="Write your custom warning message here..."
                      required
                    />
                    {selectedTemplate && (
                      <button
                        type="button"
                        onClick={() => handleEditTemplate(selectedTemplate)}
                        className="text-xs font-semibold text-status-info hover:underline"
                      >
                        Edit this template
                      </button>
                    )}
                  </div>
                ) : (
                  <div className="space-y-2">
                    <div id="warn-message" className="bg-background border border-border rounded-tile p-3">
                      <p className="m-0 text-xs text-ink">{customMessage || 'Select a template or use AI to generate a message'}</p>
                    </div>
                    {selectedTemplate && (
                      <button
                        type="button"
                        onClick={() => handleEditTemplate(selectedTemplate)}
                        className="text-xs font-semibold text-status-info hover:underline"
                      >
                        Edit this template
                      </button>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* AI generated message */}
            {aiAutoGenerated && (
              <div className="bg-green-tint p-4 rounded-xl border border-brand/20">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-brand" />
                    <span className="text-xs font-semibold text-brand-dark">AI Generated Warning</span>
                  </div>
                  <span className="text-xs text-brand-dark">Type: {warningType}</span>
                </div>
                <div className="bg-white p-3 rounded-lg border border-border">
                  <p className="m-0 text-xs text-ink whitespace-pre-wrap">{customMessage}</p>
                </div>
                <div className="flex justify-between items-center mt-3">
                  <p className="m-0 text-[11px] text-brand-dark">Message generated from your description.</p>
                  <button
                    type="button"
                    onClick={() => {
                      setUseCustomMessage(true);
                      setAiAutoGenerated(false);
                    }}
                    className="text-xs font-semibold text-status-info hover:underline"
                  >
                    Edit Message
                  </button>
                </div>
              </div>
            )}

            <div className="flex justify-end gap-2.5 pt-2">
              <Button variant="secondary" onClick={() => setShowForm(false)}>Cancel</Button>
              <Button
                type="submit"
                className="!bg-status-danger !border-status-danger"
                disabled={sending || employees.length === 0 || (!customMessage.trim())}
                icon={sending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Mail className="w-3.5 h-3.5" />}
              >
                {sending ? 'Sending...' : 'Send Warning'}
              </Button>
            </div>
          </form>
        </Card>
      )}

      {/* Warning history */}
      <Card padding="none" className="overflow-hidden">
        <div className="px-5 py-3.5 border-b border-border flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <h2 className="m-0 text-sm font-bold text-ink">Warning History</h2>
          {filteredWarnings.length > 0 && (
            <p className="m-0 text-xs text-muted-foreground">
              Showing {startIndex + 1}-{Math.min(startIndex + itemsPerPage, filteredWarnings.length)} of {filteredWarnings.length} warnings
            </p>
          )}
        </div>

        {filteredWarnings.length === 0 ? (
          <EmptyState
            className="py-12"
            icon={<AlertTriangle size={20} />}
            title={warningSearchTerm ? 'No matching warnings found' : 'No warnings issued'}
            description={warningSearchTerm ? 'Try a different search term' : 'Issued warnings will appear here for record keeping.'}
          />
        ) : (
          <>
            <div>
              {paginatedWarnings.map(warning => (
                <div key={warning.id} className="px-5 py-3.5 border-b border-[#F1F5F2] hover:bg-background transition-colors">
                  <div className="flex items-center gap-2.5 mb-1.5">
                    <h3 className="m-0 text-xs font-bold text-ink">
                      {warning.employeeData?.fullName || 'Unknown Employee'}
                    </h3>
                    <StatusPill label={warning.severity} tone={severityTone(warning.severity)} className="capitalize" />
                  </div>

                  <div className="flex flex-wrap items-center gap-4 mb-1.5 text-[11px] text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Mail className="w-3 h-3" />
                      {warning.employeeData?.email || 'No email'}
                    </span>
                    <span className="flex items-center gap-1">
                      <Building className="w-3 h-3" />
                      {warning.employeeData?.department || 'No department'}
                    </span>
                    <span className="flex items-center gap-1">
                      <BadgeAlert className="w-3 h-3" />
                      ID: {warning.employee_id}
                    </span>
                  </div>

                  <p className="m-0 text-xs text-ink mb-1.5 leading-relaxed">{warning.message}</p>

                  <div className="flex items-center text-[11px] text-subtle">
                    <Calendar className="w-3 h-3 mr-1" />
                    {new Date(warning.issued_at).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'short',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                    <span className="mx-2">•</span>
                    <FileText className="w-3 h-3 mr-1" />
                    {warning.type}
                  </div>
                </div>
              ))}
            </div>

            {totalPages > 1 && (
              <div className="border-t border-border px-5 py-3 flex items-center justify-between">
                <div className="text-xs text-muted-foreground">
                  Page {currentPage} of {totalPages}
                </div>
                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    aria-label="Previous page"
                    onClick={() => handlePageChange(currentPage - 1)}
                    disabled={currentPage === 1}
                    className="p-1.5 rounded-lg border border-border bg-white text-muted-foreground hover:bg-secondary disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    <ChevronLeft className="w-4 h-4" />
                  </button>

                  {getPageNumbers().map((page, index) => (
                    <button
                      type="button"
                      key={index}
                      onClick={() => typeof page === 'number' ? handlePageChange(page) : null}
                      disabled={page === '...'}
                      className={`min-w-[2.25rem] px-2 py-1 rounded-lg border text-xs transition-colors ${
                        currentPage === page
                          ? 'border-brand bg-green-tint text-brand font-semibold'
                          : 'border-border bg-white text-muted-foreground hover:bg-secondary'
                      } ${page === '...' ? 'cursor-default' : ''}`}
                    >
                      {page}
                    </button>
                  ))}

                  <button
                    type="button"
                    aria-label="Next page"
                    onClick={() => handlePageChange(currentPage + 1)}
                    disabled={currentPage === totalPages}
                    className="p-1.5 rounded-lg border border-border bg-white text-muted-foreground hover:bg-secondary disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </Card>
    </div>
  );
}
